
export const listOfFilm = [
    { id: '1', you: 'https://www.youtube.com/embed/IPX-L2F78fU?si=f5iMvN0i1Qe81Cb_', img: 'assets/images/aot.jpeg', title: 'Attack on Titan', year: '2009', nation: 'Japan', info: 'Attack on Titan (Japanese: 進撃の巨人, Hepburn: Shingeki no Kyojin, lit. The Advancing Giant) is a Japanese manga series written and illustrated by Hajime Isayama. It is set in a world where humanity is forced to live in cities surrounded by three enormous walls that protect them from gigantic man-eating humanoids referred to as Titans; the story follows Eren Yeager, who vows to exterminate the Titans after they bring about the destruction of his hometown and the death of his mother. It was serialized in Kodanshas monthly magazine Bessatsu Shōnen Magazine from September 2009 to April 2021, with its chapters collected in 34 tankōbon volumes.' },
    { id: '2', you: 'https://www.youtube.com/embed/gGaycBSNRzs?si=7nC2e7_3SenziItK', img: 'assets/images/grand.jpg', title: 'Grand Blue', year: '2014', nation: 'Japan', info: 'Grand Blue (ぐらんぶる, Guranburu, publishing in English version as Grand Blue Dreaming) is a Japanese manga series written by Kenji Inoue and illustrated by Kimitake Yoshioka. It has been serialized in Kodanshas seinen manga magazine good! Afternoon since April 2014. The manga is published digitally in English by Kodansha USA under the Kodansha Comics imprint. An anime television series adaptation by Zero-G aired from July to September 2018 in the Animeism programming block on MBS. A live-action film adaptation was released in August 2020.' },
    { id: '3', you: 'https://www.youtube.com/embed/5NF6B65HsIc?si=myjaDLfMBUm6z70G', img: 'assets/images/howl.jpg', title: 'Lâu Đài Di Động Của Howl', year: '2004', nation: 'Japan', info: 'Sophie (Emily Mortimer) has an uneventful life at her late fathers hat shop, but all that changes when she befriends wizard Howl (Christian Bale), who lives in a magical flying castle. However, the evil Witch of Waste (Lauren Bacall) takes issue with their budding relationship and casts a spell on young Sophie, which ages her prematurely. Now Howl must use all his magical talents to battle the jealous hag and return Sophie to her former youth and beauty.' },
    { id: '4', you: 'https://www.youtube.com/embed/7SZCvJmne-s?si=iNlkyulurey-OvOZ', img: 'assets/images/ponyo.jpg', title: 'Ponyo', year: '2008', nation: 'Japan', info: 'During a forbidden excursion to see the surface world, a goldfish princess encounters a human boy named Sosuke, who gives her the name Ponyo. Ponyo longs to become human, and as her friendship with Sosuke grows, she becomes more humanlike. Ponyos father brings her back to their ocean kingdom, but so strong is Ponyos wish to live on the surface that she breaks free, and in the process, spills a collection of magical elixirs that endanger Sosukes village.' },
    { id: '5', you: 'https://www.youtube.com/embed/mozmIkTM1pE?si=7saz6uX6OddLp10C', img: 'assets/images/naruto.jpg', title: 'Naruto', year: '1997', nation: 'Japan', info: 'Naruto[a] is a Japanese manga series written and illustrated by Masashi Kishimoto. It tells the story of Naruto Uzumaki, a young ninja who seeks recognition from his peers and dreams of becoming the Hokage, the leader of his village. The story is told in two parts: the first is set in Narutos pre-teen years (volumes 1–27), and the second in his teens (volumes 28–72). The series is based on two one-shot manga by Kishimoto: Karakuri (1995), which earned Kishimoto an honorable mention in Shueishas monthly Hop Step Award the following year, and Naruto (1997).' },
    { id: '6', you: 'https://www.youtube.com/embed/H7PPUNFOxek?si=lM-XQ5V2neqeV3wX', img: 'assets/images/umasou.jpg', title: 'You Are Umasou', year: '2010', nation: 'Japan', info: 'You Are Umasou (Japanese: おまえうまそうだな, Hepburn: Omae Umasō da na, "You look tasty") is a Japanese picture book series by Tatsuya Miyanishi, published by Poplar. The series has spawned an animated film and anime adaptations. The fourth film My Tyrano II: Easter, Garden was planned to release in 2024 but was delayed to 2025.' },
];
export const listofnews = [
   
]

